// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UNFBusShuttle.Data;

#nullable disable

namespace UNFBusShuttle.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UNFBusShuttle.Models.Schedule", b =>
                {
                    b.Property<int>("schedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("schedId"), 1L, 1);

                    b.Property<int>("adminCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("arrTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("depTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("destination")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("schedId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("UNFBusShuttle.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("UNFBusShuttle.Models.Admin", b =>
                {
                    b.HasBaseType("UNFBusShuttle.Models.User");

                    b.Property<int>("adminCode")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("UNFBusShuttle.Models.Driver", b =>
                {
                    b.HasBaseType("UNFBusShuttle.Models.User");

                    b.Property<int>("busNumber")
                        .HasColumnType("int");

                    b.Property<int>("schedId")
                        .HasColumnType("int");

                    b.Property<bool?>("status")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Driver");
                });

            modelBuilder.Entity("UNFBusShuttle.Models.Rider", b =>
                {
                    b.HasBaseType("UNFBusShuttle.Models.User");

                    b.Property<int>("nNumber")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Rider");
                });
#pragma warning restore 612, 618
        }
    }
}
